services:
    autopsy:
# if you want to build the image uncomment the next
#        build:
#         context: .
#        image: autopsy
        image: fabianastudillo/autopsy:latest
        container_name: autopsy
        shm_size: "2gb"
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
            - ./case/:/root/case
        environment:
            - DISPLAY=${DISPLAY}
            - JAVA_TOOL_OPTIONS=-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel
        networks:
            - host
#        devices:
#          - "/dev/dri:/dev/dri"


networks:
    host:
